// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOBsdkLll-kA7nIHVWDGUvNdpUKD7jpxA',
    appId: '1:866177982758:web:e1e0440177c64ac027a1e7',
    messagingSenderId: '866177982758',
    projectId: 'eye-dec',
    authDomain: 'eye-dec.firebaseapp.com',
    storageBucket: 'eye-dec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY0D4VI7e-DlnTtPdiNLd2GW_8uc6Azmo',
    appId: '1:866177982758:android:1fcf3aeec06e856227a1e7',
    messagingSenderId: '866177982758',
    projectId: 'eye-dec',
    storageBucket: 'eye-dec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgUP_KhyWGNCC92t_nkU3Gs-pOuSj3E2o',
    appId: '1:866177982758:ios:fc4d6c2af0a68b3627a1e7',
    messagingSenderId: '866177982758',
    projectId: 'eye-dec',
    storageBucket: 'eye-dec.appspot.com',
    iosClientId: '866177982758-ll1oq8er79r8vn384vc7jp78gjubtkh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.eyedecApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgUP_KhyWGNCC92t_nkU3Gs-pOuSj3E2o',
    appId: '1:866177982758:ios:fc4d6c2af0a68b3627a1e7',
    messagingSenderId: '866177982758',
    projectId: 'eye-dec',
    storageBucket: 'eye-dec.appspot.com',
    iosClientId: '866177982758-ll1oq8er79r8vn384vc7jp78gjubtkh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.eyedecApp',
  );
}
