// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtRyahYXYJRZWkVIBJhJVcyq7RZACQkL8',
    appId: '1:134410375961:web:4b5cdc55f1c1afd99d2b88',
    messagingSenderId: '134410375961',
    projectId: 'eyedecapp',
    authDomain: 'eyedecapp.firebaseapp.com',
    storageBucket: 'eyedecapp.appspot.com',
    measurementId: 'G-YS3CX8C5V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH8Rv-7EkNI-Iej5PcxTJLqom9DtclN_c',
    appId: '1:134410375961:android:ea978d529cb686549d2b88',
    messagingSenderId: '134410375961',
    projectId: 'eyedecapp',
    storageBucket: 'eyedecapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPUfJge-kRf8-UcQx8GEW5gQxAXjurg6A',
    appId: '1:134410375961:ios:7b4857695941a65f9d2b88',
    messagingSenderId: '134410375961',
    projectId: 'eyedecapp',
    storageBucket: 'eyedecapp.appspot.com',
    iosClientId: '134410375961-d5252ejfs9dh1qsbjnfk0euq98g4gsfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.eyedecFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPUfJge-kRf8-UcQx8GEW5gQxAXjurg6A',
    appId: '1:134410375961:ios:7b4857695941a65f9d2b88',
    messagingSenderId: '134410375961',
    projectId: 'eyedecapp',
    storageBucket: 'eyedecapp.appspot.com',
    iosClientId: '134410375961-d5252ejfs9dh1qsbjnfk0euq98g4gsfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.eyedecFront',
  );
}
