// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgv_aPjBxANdoxRXAmGJRR_SZ37Ybpnoo',
    appId: '1:271347922322:web:535a391df2e8653028bd4b',
    messagingSenderId: '271347922322',
    projectId: 'photo-with-oshi',
    authDomain: 'photo-with-oshi.firebaseapp.com',
    storageBucket: 'photo-with-oshi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqRsalNTclFXzEWF40-HwOuAEv3lgBiH0',
    appId: '1:271347922322:android:bb0ebfb87571c6bd28bd4b',
    messagingSenderId: '271347922322',
    projectId: 'photo-with-oshi',
    storageBucket: 'photo-with-oshi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxJUhBrA7y1FThqz5rwyzya2YyFcO2-RI',
    appId: '1:271347922322:ios:158aed3dfe555f6428bd4b',
    messagingSenderId: '271347922322',
    projectId: 'photo-with-oshi',
    storageBucket: 'photo-with-oshi.appspot.com',
    iosClientId: '271347922322-sbocb9jci3tcf6bmgcfkdh1kkq42727h.apps.googleusercontent.com',
    iosBundleId: 'com.example.photowithoshiFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxJUhBrA7y1FThqz5rwyzya2YyFcO2-RI',
    appId: '1:271347922322:ios:158aed3dfe555f6428bd4b',
    messagingSenderId: '271347922322',
    projectId: 'photo-with-oshi',
    storageBucket: 'photo-with-oshi.appspot.com',
    iosClientId: '271347922322-sbocb9jci3tcf6bmgcfkdh1kkq42727h.apps.googleusercontent.com',
    iosBundleId: 'com.example.photowithoshiFront',
  );
}
